### ISSUE TITLE
Add changelog labels and auto release notes generation config

### ISSUE THREAD

**Issue by Kamforka** [TheHive-Project/cortexutils#26]
The release notes generation config should follow the same as of thehive4py:

```yaml
changelog:
  exclude:
    labels:
      - changelog:ignore
  categories:
    - title: Added
      labels:
        - changelog:added
    - title: Changed
      labels:
        - changelog:changed
    - title: Removed
      labels:
        - changelog:removed
    - title: Deprecated
      labels:
        - changelog:deprecated
    - title: Fixed
      labels:
        - changelog:fixed
    - title: Security
      labels:
        - changelog:security
    - title: Other
      labels:
        - "*"
```
